### PR TITLE
Add Crystal icons.

### PR DESCRIPTION
**Pull request by faustinoaq**
Hi @LaurentTreguier

This PR do the following:

- Uses test icon for spec folder.
- Uses Crystal icon for [Embed Crystal](https://crystal-lang.org/api/latest/ECR.html) (ecr) files.
- Uses Crystal icon for [Crystal Slang](https://github.com/jeromegn/slang) (template engine).
- Changes Crystal icon contrast because current white and black colors are too bright.

Before: using `#ffffff`, I want to use colorful icon theme, but crystal icon is too bright currently.

screenshot_20170728_151325

After: using `#dddddd`, see `spec` folder.

screenshot_20170728_151223

BTW, excellent icon theme :+1: 

### Edit: straightened icon.

Before: 

screenshot_20170728_154329

After: apply transform

screenshot_20170728_154438

Just like favicon from crystal-lang.org

screenshot_20170728_154521

Too many details :sweat_smile:

### CODE REVIEW

**Comment by LaurentTreguier** [comment]
There are never too many details... This is why we have icons in VSCode's explorer 😄 
I tried using crystal-lang.org's favicon to make mine, however it looks like I took the wrong version with an `.ico` extension instead of `.png` (https://crystal-lang.org/favicon.ico instead of https://crystal-lang.org/favicon.png), which was not the straight icon...

What are you using to modify the icons ? I make them directly in VSCode and thus I like to keep them tidy and pixel-perfect when possible, and the straightened icon is the tilted icon with a rotation (which is not very efficient).

### EDIT 1:
On another note, I might make variations of the crystal icon for Embedded crystal and Slang.

### EDIT 2:
image

**Comment by faustinoaq** [comment]
@LaurentTreguier I use Inkscape and VSCode to edit svg files.

I like your version of crystal-embedded :heart_eyes: 

So, What change Do I need to do to get it merged?

**Comment by faustinoaq** [comment]
I'm not a designer but let me try to design crystal icon from scratch to make it pixel-perfect :smile: 

I going to take inspiration of this:

crystal icons

**Comment by LaurentTreguier** [comment]
Well, I already made some changes to be able to make this screenshot:
```diff
diff --git a/source/simple-icons/crystal.svg b/source/simple-icons/crystal.svg
index be11d5b..566ada1 100644
--- a/source/simple-icons/crystal.svg
+++ b/source/simple-icons/crystal.svg
@@ -4,8 +4,8 @@
     <defs>
         <mask id="mask">
             <rect x="0" y="0" width="320" height="320" fill="#fff"/>
-            <polygon points="20,120 160,80 120,230" fill="#000"/>
+            <polygon points="50,100 190,100 120,220" fill="#000"/>
         </mask>
     </defs>
-    <polygon points="120,0 275,45 315,200 200,320 45,275 5,120" fill="#ffffff" mask="url(#mask)"/>
+    <polygon points="160,0 300,80 300,240 160,320 20,240 20,80" fill="#dfdfdf" mask="url(#mask)"/>
 </svg>
\ No newline at end of file
```

**Comment by faustinoaq** [comment]
Excellent :+1: , so, Do I need to modify this PR with your changes?

**Comment by faustinoaq** [comment]
What are the changes did you make to get crystal-embedded?

**Comment by LaurentTreguier** [comment]
I used the crystal icon, but changed the mask to use the same as `ruby-embedded` for example.

**Comment by faustinoaq** [comment]
Much better with your changes :smile: 

screenshot_20170728_172220

Let me add crystal-embedded in other commit

**Comment by LaurentTreguier** [comment]
Oops didn't see your last comment about crystal-embedded icon... But I already got it anyway, so...

**Comment by faustinoaq** [comment]
Don't worry let me open other PR to add crystal-embedded icon :smile: 

I need to adjust the mask a bit

screenshot_20170728_173103

**Comment by LaurentTreguier** [comment]
You don't worry, the icon already exists 😄

**Comment by faustinoaq** [comment]
Thanks you so much :+1: 

Can you publish a new version on marketplace?

BTW, I use my extension [vscode-crystal-lang](https://github.com/faustinoaq/vscode-crystal-lang) to get Slang syntax and snippets

screenshot_20170728_173830

**Pull request merged**
